name: get user info

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  userinfo:
    runs-on: ubuntu-latest
    steps:
      - name: get user info
        run: |
          echo ${{github.event.pusher.name}}
      - name: condition on user name
        if: github.event.pusher.name == 'hvaldecantos'
        run: |
          echo "OK"
