name: get user info

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  userinfo:
    steps:
      - name: get user info
        run: |
          echo github.event.pusher.name
